const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const CONFLICTING_REQUEST = 409;
module.exports = {
  BAD_REQUEST, NOT_FOUND, CONFLICTING_REQUEST, UNAUTHORIZED, FORBIDDEN,
};
